version: '3.1'
services:
  webapp:
    build:
      context: .
      dockerfile: docker/webapp/Dockerfile
    ports:
    - "4000:4000"
    volumes:
    - .:/quake-stats
  postgresql:
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    ports:
      - "5432:5432"
    # image: postgres
    # restart: always
